name: Tests

on: [push, pull_request]

env:
  RELEASE: 0
  artifact: 0
  
jobs:
  osx_test:
    runs-on: macOS-latest
    env:
      BOOST_ROOT: /tmp/boost
    steps:
      - uses: actions/checkout@722adc6
      - name: Checkout Submodules
        run: git submodule update --init --recursive
      - name: Fetch Deps
        run: TEST=1 ci/actions/osx/install_deps.sh
      - name: Run Tests
        run: ci/build-travis.sh "/tmp/qt/lib/cmake/Qt5";

  clang_format:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@50fbc62
      - name: Get clang-format 8
        env: 
          DEBIAN_FRONTEND: noninteractive
        run: |
          APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add - 
          sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main' -y
          sudo apt update -y
          sudo apt install -y clang-format-8
          sudo ln -s /usr/bin/clang-format-8 /usr/bin/clang-format
      - name: Clang Format
        run: ci/check-commit-format.sh 

  gcc_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@722adc6
      - name: Checkout Submodules
        run: git submodule update --init --recursive
      - name: Fetch Deps
        run: ci/actions/linux/install_deps.sh
      - name: Run Tests
        run: docker run -v ${PWD}:/workspace nanocurrency/nano-env:gcc /bin/bash -c "cd /workspace && ./ci/build-travis.sh /usr/lib/x86_64-linux-gnu/cmake/Qt5 ${PWD}"
  
  clang_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@722adc6
      - name: Checkout Submodules
        run: git submodule update --init --recursive
      - name: Fetch Deps
        run: ci/actions/linux/install_deps.sh
      - name: Run Tests
        run: docker run -v ${PWD}:/workspace nanocurrency/nano-env:clang /bin/bash -c "cd /workspace && RELEASE=0 ASAN=0 TSAN=0 ./ci/build-travis.sh /usr/lib/x86_64-linux-gnu/cmake/Qt5 ${PWD}"

  windows_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@722adc6
      - name: Windows Defender
        run: ci/actions/windows/disable_windows_defender.ps1
      - name: Checkout Submodules
        run: git submodule update --init --recursive
      - name: Fetch Deps
        run: ci/actions/windows/install_deps.ps1
      - name: Run Tests
        run: ci/actions/windows/build.ps1
